// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTtEGttkY2LTIt1L8nyUvEGi79GRJcZo',
    appId: '1:616402181885:web:7b8cc81f46f807c0b7e894',
    messagingSenderId: '616402181885',
    projectId: 'book-room-8a3ff',
    authDomain: 'book-room-8a3ff.firebaseapp.com',
    storageBucket: 'book-room-8a3ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQV47jgwxc4eGfAP76lwt_bssMc7tgC6Q',
    appId: '1:616402181885:android:756b70070d2971abb7e894',
    messagingSenderId: '616402181885',
    projectId: 'book-room-8a3ff',
    storageBucket: 'book-room-8a3ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiXewkb86Bs58i7jzpXBNM7rFAeRHyb-c',
    appId: '1:616402181885:ios:f4ae30f665923859b7e894',
    messagingSenderId: '616402181885',
    projectId: 'book-room-8a3ff',
    storageBucket: 'book-room-8a3ff.firebasestorage.app',
    iosBundleId: 'com.example.bookRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiXewkb86Bs58i7jzpXBNM7rFAeRHyb-c',
    appId: '1:616402181885:ios:f4ae30f665923859b7e894',
    messagingSenderId: '616402181885',
    projectId: 'book-room-8a3ff',
    storageBucket: 'book-room-8a3ff.firebasestorage.app',
    iosBundleId: 'com.example.bookRoom',
  );
}
